""Mima governance test suite.

Generated by the Mima governance dashboard.
Workspace: a92d5798-9e09-4166-a9a6-9dea300aae0e

Run locally:
    pip install mima-governance
    mima test tests/test_governance.py

What this tests:
    1. All AI call sites in this repo are attested (covered by @mima.attest)
    2. Attestation coverage meets the configured threshold (default: 80%)
"""
from mima_governance.testing import GovernanceTest


class TestAttestation(GovernanceTest):
    """Verify AI call sites are governed."""

    scan_path = "."

    def test_all_calls_attested(self):
        """Every AI library call site should have an attestation."""
        result = self.scan()
        unattested = [d for d in result.detections if not d.attested]
        assert len(unattested) == 0, (
            f"{len(unattested)} unattested AI call site(s) found. "
            f"Add @mima.attest() or run `mima scan .` to see locations."
        )

    def test_coverage_threshold(self):
        """At least 80% of AI call sites must be attested."""
        result = self.scan()
        if result.total == 0:
            return  # No AI calls = pass
        coverage = result.attested / result.total * 100
        assert coverage >= 80, (
            f"Attestation coverage {coverage:.0f}% is below 80% threshold. "
            f"Run `mima scan .` to find unattested calls."
        )
